In [2]:

%load_ext rpy2.ipython

Error importing in API mode: ImportError("dlopen(/Users/eric/Documents/SchoolCourses/PaGamO/venv/lib/python3.12/site-packages/_rinterface_cffi_api.abi3.so, 0x0002): Library not loaded: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.dylib\n  Referenced from: <733B2185-C608-342F-8FC5-CF619524A0A2> /Users/eric/Documents/SchoolCourses/PaGamO/venv/lib/python3.12/site-packages/_rinterface_cffi_api.abi3.so\n  Reason: tried: '/Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.dylib' (no such file)")
Trying to import in ABI mode.
/Users/eric/Documents/SchoolCourses/PaGamO/venv/lib/python3.12/site-packages/rpy2/rinterface/__init__.py:1211: UserWarning: Environment variable "PWD" redefined by R and overriding existing variable. Current: "/Users/eric/Documents/SchoolCourses/PaGamO", R: "/Users/eric/Documents/SchoolCourses/PaGamO/analyze"
  warnings.warn(
/Users/eric/Documents/SchoolCourses/PaGamO/venv/lib/python3.12/site-packages/rpy2/rinterface/__init__.py:1211: UserWarning: Environment variable "XPC_SERVICE_NAME" redefined by R and overriding existing variable. Current: "application.com.jetbrains.dataspell.395393.6182009", R: "0"
  warnings.warn(
/Users/eric/Documents/SchoolCourses/PaGamO/venv/lib/python3.12/site-packages/rpy2/rinterface/__init__.py:1211: UserWarning: Environment variable "R_SESSION_TMPDIR" redefined by R and overriding existing variable. Current: "/var/folders/n9/jhsz5r6d6cvctky31mq3pnfr0000gn/T//RtmpyYY53L", R: "/var/folders/n9/jhsz5r6d6cvctky31mq3pnfr0000gn/T//RtmpOyEyMA"
  warnings.warn(

# setting env.

In [3]:
from docutils.nodes import target
from scipy.stats import lognorm
from statsmodels.iolib.summary import summary

import os
from pathlib import Path
from unicodedata import category

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.font_manager import fontManager
import seaborn as sns
import duckdb
import statistics
import pandas as pd
import numpy as np
import functools
from IPython.core.pylabtools import figsize
from matplotlib.lines import lineStyles
from matplotlib.pyplot import xlabel, tight_layout
import os
import statsmodels.formula.api as smf

In [4]:
fontManager.get_font_names()

['Charmonman',
 'Noto Sans Masaram Gondi',
 'Sama Tamil',
 'Noto Serif Hmong Nyiakeng',
 'BM Jua',
 'Tiro Devanagari Marathi',
 'Jaini Purva',
 'Menlo',
 'Bradley Hand',
 '.New York',
 'Bodoni 72',
 'cmmi10',
 'Arima Madurai',
 'Wingdings 3',
 'Adelle Sans Devanagari',
 'Noto Sans Inscriptional Pahlavi',
 'Apple LiGothic',
 'YuGothic',
 'STIX Two Text',
 'Noto Sans Wancho',
 'Baloo Bhai 2',
 'Hiragino Sans TC',
 'Geneva',
 'STIXSizeOneSym',
 'Didot',
 'Noto Sans Multani',
 'Noto Sans Khudawadi',
 'Yuanti SC',
 'October Tamil',
 'Noto Sans Tifinagh',
 'Noto Sans Tai Tham',
 'Avenir Next',
 'Noto Sans Mandaic',
 'Skia',
 'Noto Sans Cypriot',
 'Gill Sans',
 'DejaVu Sans Mono',
 'Noto Sans Palmyrene',
 'Noto Sans Warang Citi',
 'Palatino',
 'Kannada MN',
 'Tamil Sangam MN',
 'Noto Sans Linear B',
 'Mshtakan',
 'Mukta Vaani',
 'Nadeem',
 'KoHo',
 'Noto Sans Kayah Li',
 'Al Nile',
 'Thonburi',
 'Wingdings',
 'Noto Sans Limbu',
 'Noto Sans Newa',
 'Noto Sans Elbasan',
 'Tiro Gurmukhi',
 'Noto Sans Rejang',
 'Baoli SC',
 'Yuppy SC',
 'Noto Sans Lisu',
 'Yuppy TC',
 '.SF Hebrew Rounded',
 'Noto Serif Kannada',
 'October Condensed Devanagari',
 'Georgia',
 'Niramit',
 'Noto Sans Lepcha',
 'Futura',
 'Times New Roman',
 'Mali',
 'Arima Koshi',
 'Kohinoor Gujarati',
 'Jaini',
 'Noto Sans Adlam',
 'October Devanagari',
 'Noto Sans Takri',
 'Noto Sans Yi',
 'Noto Sans Osage',
 'Hei',
 'Noto Sans Egyptian Hieroglyphs',
 'New Peninim MT',
 'cmsy10',
 'Sama Devanagari',
 'Kaiti SC',
 'Noto Sans NKo',
 'Marion',
 'Snell Roundhand',
 'Noto Serif Myanmar',
 'Noto Sans Phoenician',
 'Hiragino Mincho ProN',
 'Cochin',
 'Apple Chancery',
 'Kavivanar',
 'Tamil MN',
 'Tiro Bangla',
 'Ayuthaya',
 'Noto Sans Tirhuta',
 'Phosphate',
 'Noto Sans Lycian',
 'October Compressed Devanagari',
 'Khmer MN',
 'LiSong Pro',
 'Noto Sans Oriya',
 'Avenir',
 'DejaVu Serif Display',
 'STIXIntegralsSm',
 'Noto Sans Old Permic',
 'Diwan Thuluth',
 'Katari',
 'Noto Sans Khojki',
 'Charter',
 'Trebuchet MS',
 'Courier New',
 'Baloo Da 2',
 'Noto Sans Hanifi Rohingya',
 'LingWai TC',
 'Optima',
 'Hiragino Sans',
 'PilGi',
 'Noto Sans Thaana',
 'Noto Sans Cuneiform',
 'Sana',
 'Noto Sans Kharoshthi',
 'DejaVu Sans Display',
 'PT Serif Caption',
 'PT Mono',
 'Xingkai SC',
 '.SF Compact',
 'HanziPen SC',
 'Lahore Gurmukhi',
 'Krungthep',
 'Noto Sans Bassa Vah',
 'Noto Sans Gunjala Gondi',
 'Noto Sans Old South Arabian',
 'BM Yeonsung',
 'Baloo Bhaina 2',
 'AkayaTelivigala',
 'Arial Black',
 'Papyrus',
 '.SF Armenian',
 'Sinhala Sangam MN',
 'Noto Sans Pahawh Hmong',
 'Arial Narrow',
 'cmtt10',
 'Lao Sangam MN',
 'Baloo Tammudu 2',
 'cmr10',
 'Toppan Bunkyu Mincho',
 'Kai',
 'October Compressed Tamil',
 'Noto Sans Glagolitic',
 'STIXNonUnicode',
 'Kefa',
 'Noto Sans Hanunoo',
 'American Typewriter',
 'Malayalam Sangam MN',
 'STIXIntegralsUp',
 'Wingdings 2',
 'Noto Sans Tai Le',
 'DIN Condensed',
 'Noto Sans Linear A',
 'Euphemia UCAS',
 '.Keyboard',
 'STIXSizeFourSym',
 'Klee',
 'STHeiti',
 'Noto Sans Mahajani',
 'Andale Mono',
 'Noto Sans Hatran',
 'Galvji',
 'Microsoft Sans Serif',
 'Oriya Sangam MN',
 'Apple Symbols',
 'Noto Sans Gothic',
 'Noto Nastaliq Urdu',
 'Noto Sans Old Turkic',
 'cmb10',
 'Fahkwang',
 'Kohinoor Telugu',
 'Hoefler Text',
 'Heiti TC',
 'Noto Sans Old Persian',
 'Mishafi',
 'Sarabun',
 'Noto Sans Myanmar',
 'STIXVariants',
 'STIXSizeThreeSym',
 'Apple Braille',
 'Arial Unicode MS',
 'Academy Engraved LET',
 'Noteworthy',
 'LingWai SC',
 'Charm',
 'PT Serif',
 'Wawati TC',
 'Chalkboard SE',
 'STIXIntegralsUpD',
 'Hiragino Sans CNS',
 'Noto Sans Kannada',
 'PT Sans',
 'Devanagari MT',
 'Noto Sans Mende Kikakui',
 'Chalkboard',
 'Telugu MN',
 'Noto Sans Ugaritic',
 'BM Hanna 11yrs Old',
 'Waseem',
 'cmss10',
 'Bangla MN',
 'PCMyungjo',
 'Tiro Devanagari Hindi',
 'Gujarati MT',
 'Myanmar MN',
 'Noto Sans Imperial Aramaic',
 'Arial Hebrew',
 'Mukta Mahee',
 'Noto Sans New Tai Lue',
 '.CJK Symbols Fallback HK',
 '.SF Soft Numeric',
 'Zapfino',
 'Apple LiSung',
 'Noto Sans Caucasian Albanian',
 'AppleMyungjo',
 'Baloo Chettan 2',
 'Toppan Bunkyu Midashi Mincho',
 'Bangla Sangam MN',
 'Noto Sans Chakma',
 'Noto Sans Pau Cin Hau',
 'Bai Jamjuree',
 'Arial',
 'Kohinoor Bangla',
 '.SF Camera',
 'Khmer Sangam MN',
 'BIZ UDMincho',
 'GungSeo',
 'Gurmukhi MT',
 '.SF Georgian',
 'Noto Sans Sora Sompeng',
 'Kodchasan',
 'Tsukushi A Round Gothic',
 'Big Caslon',
 'Padyakke Expanded One',
 'AppleGothic',
 '.SF Armenian Rounded',
 'STIXIntegralsUpSm',
 'AkayaKanadaka',
 'Noto Sans Ol Chiki',
 'Copperplate',
 'Geeza Pro',
 'STIXSizeTwoSym',
 'Shree Devanagari 714',
 'HeadLineA',
 'Noto Sans Miao',
 'Baloo Paaji 2',
 'Lantinghei SC',
 'Courier',
 'Tiro Telugu',
 'DejaVu Serif',
 'YuKyokasho Yoko',
 'Corsiva Hebrew',
 'Bodoni 72 Smallcaps',
 'Party LET',
 'Hannotate SC',
 'Baskerville',
 '.SF Georgian Rounded',
 'Wawati SC',
 'STIXIntegralsD',
 'Telugu Sangam MN',
 '.SF NS Mono',
 'Brush Script MT',
 'Herculanum',
 'Raanana',
 'Muna',
 'Noto Sans Tagalog',
 'System Font',
 'Seravek',
 'Trattatello',
 'Baloo Bhaijaan',
 'Noto Sans Saurashtra',
 'Modak',
 'Noto Sans Carian',
 'Noto Serif Yezidi',
 'Noto Sans Sundanese',
 'DecoType Naskh',
 'Noto Serif Balinese',
 'Farisi',
 'Baghdad',
 'Helvetica',
 'Tiro Devanagari Sanskrit',
 'Lava Telugu',
 'Plantagenet Cherokee',
 'InaiMathi',
 'Noto Sans Armenian',
 'October Condensed Tamil',
 'Osaka',
 'Arial Rounded MT Bold',
 'Srisakdi',
 'Maku',
 'Noto Sans Vai',
 'Bodoni Ornaments',
 'Damascus',
 'KufiStandardGK',
 'STIXSizeFiveSym',
 'Symbol',
 'Lao MN',
 'Noto Sans PhagsPa',
 'Lava Devanagari',
 'Sathu',
 'STFangsong',
 'Kailasa',
 'Noto Sans Bamum',
 'Monaco',
 'PingFang HK',
 'Noto Sans Buhid',
 '.Aqua Kana',
 'Lucida Grande',
 'Baloo Thambi 2',
 'Helvetica Neue',
 'Noto Sans Kaithi',
 'Impact',
 'Krub',
 'Lava Kannada',
 'DIN Alternate',
 'Gurmukhi Sangam MN',
 'Malayalam MN',
 'STIX Two Math',
 'Superclarendon',
 'Iowan Old Style',
 '.SF NS Rounded',
 'Sama Malayalam',
 'Devanagari Sangam MN',
 'Comic Sans MS',
 'Noto Sans Inscriptional Parthian',
 'Chalkduster',
 'Diwan Kufi',
 '.SF Hebrew',
 'DejaVu Sans',
 '.SF Compact Rounded',
 'Savoye LET',
 'Noto Sans Mongolian',
 'Shobhika',
 'Apple SD Gothic Neo',
 'Noto Serif Ahom',
 'Kokonor',
 'Sama Gurmukhi',
 'Tahoma',
 'Nanum Myeongjo',
 'SignPainter',
 'Cambay Devanagari',
 'Noto Sans Batak',
 'Chakra Petch',
 'Silom',
 'Noto Sans Mro',
 'Nanum Gothic',
 'STIXGeneral',
 'Noto Sans Syriac',
 'Noto Sans Meroitic',
 'Webdings',
 'BM Hanna Pro',
 'Baloo Tamma 2',
 'Noto Sans Coptic',
 'Oriya MN',
 'Baloo 2',
 'Noto Sans Tagbanwa',
 'Times',
 'Noto Sans Psalter Pahlavi',
 'Noto Sans Lydian',
 'Gujarati Sangam MN',
 'Mishafi Gold',
 'BM Hanna Air',
 '.DecoType Nastaleeq Urdu UI',
 'Avenir Next Condensed',
 'Noto Sans Old Hungarian',
 'BM Dohyeon',
 'K2D',
 'Noto Sans Meetei Mayek',
 'Myanmar Sangam MN',
 'BIZ UDGothic',
 'Libian SC',
 'Farah',
 'Rockwell',
 'LiHei Pro',
 'Noto Sans Manichaean',
 'BiauKaiHK',
 'Noto Sans Bhaiksuki',
 'Mukta Malar',
 'Tsukushi B Round Gothic',
 'Noto Sans Buginese',
 'Nanum Brush Script',
 'Noto Sans Tai Viet',
 'Sukhumvit Set',
 'Tiro Tamil',
 'PSL Ornanong Pro',
 'Sama Kannada',
 'Noto Sans Old North Arabian',
 'Hiragino Sans GB',
 'Noto Sans Canadian Aboriginal',
 'Noto Sans Modi',
 'Toppan Bunkyu Midashi Gothic',
 'BM Kirang Haerang',
 'Bodoni 72 Oldstyle',
 'Noto Sans Nabataean',
 'Al Tarikh',
 'YuMincho',
 'ITF Devanagari',
 'Zapf Dingbats',
 'Gotu',
 'Noto Sans Samaritan',
 'Kohinoor Devanagari',
 'Hubballi',
 'Toppan Bunkyu Gothic',
 'SimSong',
 'Mukta',
 'Luminari',
 'Gurmukhi MN',
 'Verdana',
 'Noto Sans Duployan',
 'Hiragino Maru Gothic Pro',
 'Sama Gujarati',
 'Noto Sans Avestan',
 'Noto Sans Siddham',
 'Athelas',
 'Noto Sans Cham',
 '.SF Arabic',
 '.SF Arabic Rounded',
 'Beirut',
 'Annai MN',
 'Noto Sans Syloti Nagri',
 'Noto Sans Sharada',
 'Noto Sans Javanese',
 'Noto Sans Osmanya',
 'Marker Felt',
 'cmex10',
 'Noto Sans Old Italic',
 'Songti SC',
 'Sinhala MN',
 'Noto Sans Marchen',
 'Al Bayan',
 'Kannada Sangam MN',
 'Noto Sans Brahmi',
 'Tiro Kannada',
 '.ThonburiUI']

In [5]:
import matplotlib
from matplotlib.font_manager import fontManager
matplotlib.rc('font',family = ['Times New Roman','Apple LiGothic'])

group_translate = {
    -1:'Group -1 (not in experiment)',
    0:'Group 0 (random)',
    1:'Group 1 (easy)',
    2:'Group 2 (easy to hard)',
    3:'Group 3 (hard to easy)'
}

# import data

In [6]:

os.getcwd()
df_question = pd.read_parquet("../data/raw/experiment-2025-q1/ntuecon_experiment_250525/question_structure.parquet")

#conn = duckdb.connect("./data/raw/experiment-2025-q1/ntuecon_experiment_250525/target_book_volume_log.parquet")
df_book_vol = pd.read_parquet(
    "../data/raw/experiment-2025-q1/ntuecon_experiment_250603/target_book_volume_log_2025-06-03.parquet")

#conn = duckdb.connect("./data/raw/experiment-2025-q1/ntuecon_experiment_250525/target_user_answer_log.parquet")
df_user_ans = pd.read_parquet(
    "../data/raw/experiment-2025-q1/ntuecon_experiment_250603/target_user_answer_log_2025-06-03.parquet")

#conn = duckdb.connect("./data/raw/experiment-2025-q1/ntuecon_experiment_250525/target_user_info.parquet")
df_user_info = pd.read_parquet(
    "../data/raw/experiment-2025-q1/ntuecon_experiment_250603/target_user_info_2025-06-03.parquet")

df_question = pd.read_parquet(
    "../data/raw/experiment-2025-q1/ntuecon_experiment_250525/question_structure.parquet")
df_user_ans_05 = pd.read_parquet(
    "../data/raw/experiment-2025-q1/ntuecon_experiment_250525/target_user_answer_log.parquet")
df_user_info_05 = pd.read_parquet(
    '../data/raw/experiment-2025-q1/ntuecon_experiment_250603/target_user_answer_log_2025-06-03.parquet')
daily_stat = pd.read_parquet(
    '../data/raw/experiment-2025-q1/ntuecon_experiment_250603/target_gc_daily_stat_2025-06-03.parquet')
course = pd.read_parquet(
    "../data/raw/experiment-2025-q1/ntuecon_experiment_250603/target_gc_course_2025-06-03.parquet")

In [7]:
df_question

,answer,status,difficulty_level,publisher,subject_name,book_volume_name,book_volume_year,book_volume_semester,book_volume_grade,section_name,book_volume_id,question_id,section_id
0,"[""B""]",deleted,1,康軒國小,None,None,None,<NA>,<NA>,None,<NA>,-6405624640022549461,<NA>
1,"[""C""]",deleted,1,康軒國小,None,None,None,<NA>,<NA>,None,<NA>,-3028868083937169421,<NA>
2,"[""A""]",deleted,2,康軒國小,None,None,None,<NA>,<NA>,None,<NA>,-8227513203886414362,<NA>
3,"[""C""]",deleted,2,康軒國小,None,None,None,<NA>,<NA>,None,<NA>,-6238923863858885195,<NA>
4,"[""B""]",deleted,3,康軒國小,None,None,None,<NA>,<NA>,None,<NA>,3299916324537394474,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306424,"[""A""]",released,3,康軒國小,國語,四上113,113,0,<NA>,10 奇幻旋律,-7933997964409526370,3813914640257517845,-5909358065647070863
1306425,"[""A""]",released,1,康軒國中,社會,一上 113,113,0,7,06.社區與部落,-7177646212519467431,-7526009218465305760,-8720079213887773718
1306426,"[""A""]",released,2,康軒國中,社會,一上 113,113,0,7,06.社區與部落,-7177646212519467431,-511847278423702124,-8720079213887773718
1306427,"[""A""]",released,1,康軒國小,數學,四下113,113,0,<NA>,3 概數,-8538342032344072608,3053747046658221703,-7309289670126621399
1306428,"[""A""]",released,2,康軒國小,數學,四下113,113,0,<NA>,3 概數,-8538342032344072608,4142937963535847657,-7309289670126621399

In [8]:
df_book_vol

,id,user_id,gamecharacter_id,question_id,section_id,experiment_index,is_correct,created_at_utc8
0,-9053486455629282188,-1873430623263824362,-3402899112114895338,-5263639425820740356,-247801341597882458,0,0,2025-05-29 06:52:22
1,-628638455526084906,2539810456371290704,-5249020576050934100,-1897899015581030178,-247801341597882458,3,0,2025-05-29 07:08:37
2,5423695897606456782,4482546256344472469,-2519851847852223272,-3286862775113972652,-247801341597882458,1,1,2025-05-29 07:45:25
3,1009007262984326475,-1873430623263824362,-3402899112114895338,7246391716930387719,-247801341597882458,0,1,2025-05-29 06:49:05
4,8064186596603043880,4482546256344472469,-2519851847852223272,-5263639425820740356,-247801341597882458,1,0,2025-05-29 07:46:38
...,...,...,...,...,...,...,...,...
246202,1201833934479361621,6734848257007407643,-2380458800220678416,4640276776666593089,7685579370828672563,1,1,2025-05-06 14:03:10
246203,-8993535108970590512,6734848257007407643,-2380458800220678416,-4699624724852261829,7685579370828672563,1,0,2025-05-06 22:13:41
246204,-8547902248052557073,6734848257007407643,-2380458800220678416,-6428332898488313044,7685579370828672563,1,0,2025-05-06 14:09:31
246205,-1488249688878383059,8871704772713769416,7551657636002764410,689176003033462362,7685579370828672563,3,0,2025-05-06 12:29:17
246206,259653037916516921,6734848257007407643,-2380458800220678416,-2817966775693365305,7685579370828672563,1,0,2025-05-06 14:08:11

In [9]:
testdff = pd.read_json("../data/processed/session_data_new.json")
testdff.info()
testdff['is_homo'] = testdff.section_id.apply(lambda x: all(xi == x[0] for xi in x))
testdff.head()

<class 'pandas.core.frame.DataFrame'>
Index: 36032 entries, (-9216223767477519093, -3293706459053707777, 1) to (9223087356083948458, 8730877631531542123, 1)
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               36032 non-null  int64
 1   gamecharacter_id      36032 non-null  int64
 2   session_id            36032 non-null  int64
 3   is_correct            36032 non-null  object
 4   difficulty_level      36032 non-null  object
 5   experiment_index      36032 non-null  object
 6   question_id           36032 non-null  object
 7   subject_name          36032 non-null  object
 8   section_id            36032 non-null  object
 9   section_name          36032 non-null  object
 10  school_city           36032 non-null  object
 11  created_at            36032 non-null  object
 12  answer                36032 non-null  object
 13  book_volume_name      36032 non-null  object
 14  is_self_selected      36032 non-null  object
 15  manual_book_vol       36032 non-null  object
 16  time_diff             36032 non-null  object
 17  created_at_utc8       36032 non-null  object
 18  start_time            36032 non-null  datetime64[ns]
 19  end_time              36032 non-null  datetime64[ns]
 20  session_length        36032 non-null  int64
 21  answer_length         36032 non-null  int64
 22  experiment_mode       14157 non-null  float64
 23  manual_book_vol_mode  36032 non-null  int64
 24  subject_name_mode     36032 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(6), object(16)
memory usage: 7.1+ MB

,user_id,gamecharacter_id,session_id,is_correct,difficulty_level,experiment_index,question_id,subject_name,section_id,section_name,...,time_diff,created_at_utc8,start_time,end_time,session_length,answer_length,experiment_mode,manual_book_vol_mode,subject_name_mode,is_homo
"(-9216223767477519093, -3293706459053707777, 1)",-9216223767477519093,-3293706459053707777,1,"[0, 0, 1, 0]","[1, 3, 3, 3]","[None, None, None, None]","[941132157500741589, -2528918832815624142, 603...","[數學, 數學, 數學, 數學]","[6084119510007883763, 6084119510007883763, 522...","[4 小數的乘法, 4 小數的乘法, 2 分數的計算, 2 分數的計算]",...,"[None, 19.0, 84.0, 30.0]","[1742298161000, 1742298180000, 1742298264000, ...",2025-03-18 11:42:41,2025-03-18 11:44:54,133,4,NaN,5,數學,False
"(-9215975131138636025, 2806305522055252713, 1)",-9215975131138636025,2806305522055252713,1,"[1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, ...","[1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[5986642740406154097, -1814475752912975980, 57...","[數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數...","[-247801341597882458, -247801341597882458, -24...","[1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體...",...,"[None, 102.0, 55.0, 13.0, 10.0, 16.0, 120.0, 1...","[1744596091000, 1744596193000, 1744596248000, ...",2025-04-14 02:01:31,2025-04-14 02:20:41,1150,35,1.0,5,數學,False
"(-9212166316050044816, 5893252723684985621, 1)",-9212166316050044816,5893252723684985621,1,"[1, 0, 1, 0, 1]","[1, 1, 2, 2, 1]","[None, None, None, None, None]","[-3982380057634078317, 6534779973756457463, -8...","[數學, 數學, 數學, 數學, 數學]","[-5730797827999106544, -1882325247118400549, 7...","[8-1 平行四邊形的面積, 9-1 分數表示整數相除的結果, 10-3 幾分之幾圖, 7-...",...,"[None, 13.0, 58.0, 40.0, 1580.0]","[1744897914000, 1744897927000, 1744897985000, ...",2025-04-17 13:51:54,2025-04-17 14:20:05,1691,5,NaN,5,數學,False
"(-9212166316050044816, 5893252723684985621, 2)",-9212166316050044816,5893252723684985621,2,"[1, 1, 1, 1, 1, 1, 1]","[1, 2, 2, 2, 2, 1, 1]","[3, 3, 3, 3, 3, 3, 3]","[5986642740406154097, -1814475752912975980, 48...","[數學, 數學, 數學, 數學, 數學, 數學, 數學]","[-247801341597882458, -247801341597882458, -24...","[1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積]",...,"[1940.0, 93.0, 60.0, 93.0, 33.0, 14.0, 41.0]","[1744901545000, 1744901638000, 1744901698000, ...",2025-04-17 14:52:25,2025-04-17 14:57:59,334,7,3.0,5,數學,True
"(-9188432125589223658, -3468651825129845530, 1)",-9188432125589223658,-3468651825129845530,1,"[0, 0]","[2, 1]","[None, None]","[-8645121234103906346, 6775587959579167004]","[數學, 數學]","[1466806251755821696, 1466806251755821696]","[8 分數, 8 分數]",...,"[None, 6.0]","[1744018600000, 1744018606000]",2025-04-07 09:36:40,2025-04-07 09:36:46,6,2,NaN,4,數學,True

# Separate sessions by sections(章節)

In [10]:
# trasform data to seperate different character
long_data = pd.DataFrame()
diff_list = []
corr_list = []
question_list = []
user_id = []
session_id = []
gamecharacter_id = []
section_id = []
experiment_index = []
experiment_mode = []
create_time = []

for idx, row in testdff.iterrows():
    section_set = list(set(row.section_id))
    for sec in section_set:
        section_id.append(sec)
        user_id.append(row.user_id)
        session_id.append(row.session_id)
        gamecharacter_id.append(row.gamecharacter_id)
        experiment_mode.append(row.experiment_mode)
        experiment_index.append([row.experiment_index[idx] for idx, x in enumerate(row.section_id) if x == sec])
        diff_list.append([row.difficulty_level[idx] for idx, x in enumerate(row.section_id) if x == sec])
        corr_list.append([row.is_correct[idx] for idx, x in enumerate(row.section_id) if x == sec])
        question_list.append([row.question_id[idx] for idx, x in enumerate(row.section_id) if x == sec])
        create_time.append([pd.to_datetime(row.created_at_utc8[idx],unit='ms')  for idx, x in enumerate(row.section_id) if x == sec])

long_data['user_id'] = user_id
long_data['session_id'] = session_id
long_data['gamecharacter_id'] = gamecharacter_id
long_data['section_id'] = section_id
long_data['difficulty_level'] = diff_list
long_data['is_correct'] = corr_list
long_data['question_id'] = question_list
long_data['experiment_index'] = experiment_index
long_data['experiment_mode'] = experiment_mode
long_data['create_time'] = create_time

In [11]:
long_data['experiment_mode'] = long_data['experiment_mode'].fillna(-1)
#long_data = long_data.drop_duplicates(subset=['section_id','user_id','gamecharacter_id'])
long_data.to_json('../data/processed/session_by_section_data_new.json')
long_data.value_counts('experiment_mode')

experiment_mode
-1.0    53918
 1.0     7987
 0.0     7878
 2.0     7313
 3.0     6727
Name: count, dtype: int64

# regression analyze
- different way to control difficulty sequences
    - number of different difficulty
    - each combination as a one-hot coding (should be limit in length 7~8 ? ,which is 2^7 = 128 )
    - average of difficulty

In [12]:
from typing import Callable


def generate_data(df:pd.DataFrame,
                  pre_test_interval:tuple[int,int]|int,
                  treatment_interval:tuple[int,int]|int,
                  after_test: tuple[int,int]|int,
                  translate_treatment_func: Callable[[list|int],None] | None ):
    for qid in range(12):
        df[f'q_{qid + 1}'] = df['question_id'].apply(lambda x: x[qid] if qid < len(x) else None)
        df[f'q_{qid + 1}_corr'] = df['is_correct'].apply(lambda x: int(x[qid]) if qid < len(x) else None)
        df[f'q_{qid + 1}_diff'] = df['difficulty_level'].apply(lambda x: int(x[qid]) if qid < len(x) else None)

    if isinstance(pre_test_interval,tuple):
        qfst = pre_test_interval[0] - 1
        qfin = pre_test_interval[1] - 1
        df['pre_test_corr'] = df['is_correct'].apply(lambda x: x[qfst:qfin+1] if qfin < len(x) else None)
        df['pre_test_diff'] = df['difficulty_level'].apply(lambda x: x[qfst:qfin+1] if qfin < len(x) else None)
    else:
        qidex = pre_test_interval - 1
        df['pre_test_corr'] = df["is_correct"].apply(lambda x : x[qidex] if qidex < len(x) else None)
        df['pre_test_diff'] = df['difficulty_level'].apply(lambda x : x[qidex] if qidex < len(x) else None)

    if isinstance(treatment_interval, tuple):
        qfst = treatment_interval[0] - 1
        qfin = treatment_interval[1] - 1
        df['treatment_corr'] = df['is_correct'].apply(lambda x:x[qfst:qfin+1] if qfin < len(x) else None)
        df['treatment_diff'] = df['difficulty_level'].apply(lambda x: x[qfst:qfin+1] if qfin < len(x) else None)
    else:
        qidex = treatment_interval - 1
        df['treatment_corr'] = df["is_correct"].apply(lambda x : x[qidex] if qidex < len(x) else None)
        df['treatment_diff'] = df['difficulty_level'].apply(lambda x : x[qidex] if qidex < len(x) else None)

    if isinstance(after_test,tuple):
        qfst = after_test[0] - 1
        qfin = after_test[1] - 1
        df['after_test_corr'] = df['is_correct'].apply(lambda x:x[qfst:qfin+1] if qfin < len(x) else None)
        df['after_test_diff'] = df['difficulty_level'].apply(lambda x: x[qfst:qfin+1] if qfin < len(x) else None)
    else:
        qidex = after_test - 1
        df['after_test_corr'] = df["is_correct"].apply(lambda x : x[qidex] if qidex < len(x) else None)
        df['after_test_diff'] = df['difficulty_level'].apply(lambda x : x[qidex] if qidex < len(x) else None)

    if translate_treatment_func is not None:
        df['treatment'] = df['treatment_diff'].apply(lambda x : translate_treatment_func(x))

    return df

In [13]:
treatment_one_hot_coding = {
    (i, j, k): int(idx)
    for idx, (i, j, k) in enumerate(
        [(a, b, c) for a in range(1, 4) for b in range(1, 4) for c in range(1, 4)],
        start=1
        )
    }

def translate_func_count(lis):
    if lis is None:
        return None
    cates = [1,2,3]
    nums = [ lis.count(lev) for lev in cates]
    return nums

def treatment_one_hot_coding_func(input):
    if input is None:
        return None
    input = tuple(input)
    return treatment_one_hot_coding.get(input,None)

In [14]:
print(treatment_one_hot_coding)

{(1, 1, 1): 1, (1, 1, 2): 2, (1, 1, 3): 3, (1, 2, 1): 4, (1, 2, 2): 5, (1, 2, 3): 6, (1, 3, 1): 7, (1, 3, 2): 8, (1, 3, 3): 9, (2, 1, 1): 10, (2, 1, 2): 11, (2, 1, 3): 12, (2, 2, 1): 13, (2, 2, 2): 14, (2, 2, 3): 15, (2, 3, 1): 16, (2, 3, 2): 17, (2, 3, 3): 18, (3, 1, 1): 19, (3, 1, 2): 20, (3, 1, 3): 21, (3, 2, 1): 22, (3, 2, 2): 23, (3, 2, 3): 24, (3, 3, 1): 25, (3, 3, 2): 26, (3, 3, 3): 27}

In [15]:
def OLS_estimate(df:pd.DataFrame, dep_var:str, indep_var:list):
    xstr = ""
    for var in indep_var:
        xstr += f"{var} +"
    xstr = xstr[:-1]

    formula = f"{dep_var} ~ {xstr}"
    model = smf.ols(data = df, formula= formula).fit()
    print(model.summary())
    return model

In [79]:
def logit_estimate(df:pd.DataFrame, dep_var:str, indep_var:list):
    xstr = ""
    for var in indep_var:
        xstr += f"{var} +"
    xstr = xstr[:-1]

    formula = f"{dep_var} ~ {xstr}"
    model = smf.logit(data = df, formula= formula).fit()
    print(model.summary())
    return model

# Teatment use one hot coding

In [16]:
regdf = generate_data(testdff, 1, (2, 4), 5,treatment_one_hot_coding_func)

In [17]:
OLS_estimate(regdf, dep_var="q_5_corr",
             indep_var=["q_1_corr * C(q_1_diff)", "C(treatment,Treatment(reference = 1))", "C(q_5_diff)"])

                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.068
Model:                            OLS   Adj. R-squared:                  0.066
Method:                 Least Squares   F-statistic:                     55.84
Date:                Fri, 17 Oct 2025   Prob (F-statistic):               0.00
Time:                        09:54:47   Log-Likelihood:                -16359.
No. Observations:               25458   AIC:                         3.279e+04
Df Residuals:                   25424   BIC:                         3.306e+04
Df Model:                          33
Covariance Type:            nonrobust
================================================================================================================
                                                   coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
Intercept                                        0.6198      0.011     54.570      0.000       0.598       0.642
C(q_1_diff)[T.2]                                 0.0428      0.011      3.766      0.000       0.021       0.065
C(q_1_diff)[T.3]                                 0.0617      0.014      4.511      0.000       0.035       0.088
C(treatment, Treatment(reference=1))[T.2.0]      0.0050      0.014      0.352      0.725      -0.023       0.033
C(treatment, Treatment(reference=1))[T.3.0]      0.0524      0.025      2.100      0.036       0.003       0.101
C(treatment, Treatment(reference=1))[T.4.0]      0.0134      0.014      0.956      0.339      -0.014       0.041
C(treatment, Treatment(reference=1))[T.5.0]      0.0028      0.014      0.196      0.844      -0.025       0.031
C(treatment, Treatment(reference=1))[T.6.0]      0.0308      0.023      1.336      0.182      -0.014       0.076
C(treatment, Treatment(reference=1))[T.7.0]      0.0549      0.025      2.161      0.031       0.005       0.105
C(treatment, Treatment(reference=1))[T.8.0]      0.0179      0.023      0.778      0.436      -0.027       0.063
C(treatment, Treatment(reference=1))[T.9.0]     -0.0183      0.030     -0.612      0.540      -0.077       0.040
C(treatment, Treatment(reference=1))[T.10.0]     0.0385      0.013      3.078      0.002       0.014       0.063
C(treatment, Treatment(reference=1))[T.11.0]     0.0128      0.014      0.932      0.351      -0.014       0.040
C(treatment, Treatment(reference=1))[T.12.0]     0.0099      0.023      0.425      0.671      -0.036       0.056
C(treatment, Treatment(reference=1))[T.13.0]     0.0130      0.014      0.915      0.360      -0.015       0.041
C(treatment, Treatment(reference=1))[T.14.0]    -0.0025      0.012     -0.205      0.837      -0.027       0.022
C(treatment, Treatment(reference=1))[T.15.0]    -0.0339      0.019     -1.776      0.076      -0.071       0.004
C(treatment, Treatment(reference=1))[T.16.0]     0.0119      0.022      0.534      0.593      -0.032       0.056
C(treatment, Treatment(reference=1))[T.17.0]    -0.0213      0.019     -1.125      0.261      -0.058       0.016
C(treatment, Treatment(reference=1))[T.18.0]     0.0074      0.024      0.306      0.760      -0.040       0.055
C(treatment, Treatment(reference=1))[T.19.0]     0.0976      0.025      3.843      0.000       0.048       0.147
C(treatment, Treatment(reference=1))[T.20.0]    -0.0307      0.022     -1.379      0.168      -0.074       0.013
C(treatment, Treatment(reference=1))[T.21.0]     0.0052      0.030      0.175      0.861      -0.053       0.063
C(treatment, Treatment(reference=1))[T.22.0]     0.0268      0.022      1.225      0.221      -0.016       0.070
C(treatment, Treatment(reference=1))[T.23.0]    -0.0051      0.019     -0.267      0.790      -0.043       0.032
C(treatment, Treatment(reference=1))[T.24.0]    -0.0206      0.024     -0.850      0.396      -0.068       0.027
C(treatment, Treatment(reference=1))[T.25.0]     0.0154      0.031      0.505      0.613      -0.044       0.075
C(treatment, Treatment(reference=1))[T.26.0]     0.0187      0.025      0.748      0.454      -0.030       0.068
C(treatment, Treatment(reference=1))[T.27.0]     0.0528      0.026      2.008      0.045       0.001       0.104
C(q_5_diff)[T.2.0]                              -0.1435      0.006    -22.107      0.000      -0.156      -0.131
C(q_5_diff)[T.3.0]                              -0.2733      0.009    -30.150      0.000      -0.291      -0.256
q_1_corr                                         0.1726      0.010     17.344      0.000       0.153       0.192
q_1_corr:C(q_1_diff)[T.2]                       -0.0467      0.014     -3.418      0.001      -0.074      -0.020
q_1_corr:C(q_1_diff)[T.3]                       -0.0281      0.018     -1.573      0.116      -0.063       0.007
==============================================================================
Omnibus:                   327077.319   Durbin-Watson:                   1.881
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3384.259
Skew:                          -0.573   Prob(JB):                         0.00
Kurtosis:                       1.631   Cond. No.                         24.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# Treatment use number of different difficulty
- estimate in same df
- estimate in different df

## in same df
### data description

In [62]:
regdf = generate_data(testdff, 1, (2, 4), 5,translate_func_count)
for i in [1,2,3]:
    regdf[f'num_diff_{i}'] = regdf['treatment'].apply(lambda x : x[i-1] if x is not None else None)
    regdf[f'prop_diff_{i}'] = regdf['treatment'].apply(lambda x : x[i-1]/np.sum(x) if x is not None else None)

In [63]:
t1 = regdf.value_counts('num_diff_3')
t2 = regdf.value_counts('num_diff_2')
t3 = regdf.value_counts('num_diff_1')
# merge these three tables
difficulty_counts = pd.DataFrame({
    'num_diff_1': t3,
    'num_diff_2': t2,
    'num_diff_3': t1
}).fillna(0)
difficulty_counts

     num_diff_1  num_diff_2  num_diff_3
0.0        7031        5694       17878
1.0        9429       10559        6697
2.0        7360        7898        2127
3.0        3274        2943         392

In [64]:
pd.options.display.precision = 2
regdf[['answer_length','q_1_corr','q_1_diff','q_5_corr','q_5_diff','num_diff_1','num_diff_2','num_diff_3']].describe()

,answer_length,q_1_corr,q_1_diff,q_5_corr,q_5_diff,num_diff_1,num_diff_2,num_diff_3
count,36032.00,36032.00,36032.00,25458.00,25458.00,27094.00,27094.00,27094.00
mean,17.87,0.63,1.70,0.65,1.73,1.25,1.30,0.45
std,22.81,0.48,0.72,0.48,0.71,0.97,0.92,0.70
min,1.00,0.00,1.00,0.00,1.00,0.00,0.00,0.00
25%,4.00,0.00,1.00,0.00,1.00,0.00,1.00,0.00
50%,11.00,1.00,2.00,1.00,2.00,1.00,1.00,0.00
75%,24.00,1.00,2.00,1.00,2.00,2.00,2.00,1.00
max,425.00,1.00,3.00,1.00,3.00,3.00,3.00,3.00

In [59]:
pd.options.display.precision = 6

In [65]:
regdf['treatment_length'] = regdf['treatment'].apply(lambda x : np.nansum(x) if x is not None else None)
regdf.value_counts('treatment_length')

treatment_length
3.0    27094
Name: count, dtype: int64

## regression analyze

In [66]:
treatment= [f"num_diff_{i}" for i in [2,3]]
conti_indep_var = ["C(q_1_corr) : C(q_1_diff)","C(q_5_diff)"]
conti_indep_var.extend(treatment)
model = OLS_estimate(regdf, dep_var="q_5_corr", indep_var=conti_indep_var)

                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.066
Model:                            OLS   Adj. R-squared:                  0.065
Method:                 Least Squares   F-statistic:                     199.1
Date:                Fri, 17 Oct 2025   Prob (F-statistic):               0.00
Time:                        15:19:02   Log-Likelihood:                -16383.
No. Observations:               25458   AIC:                         3.279e+04
Df Residuals:                   25448   BIC:                         3.287e+04
Df Model:                           9
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.6412      0.010     64.794      0.000       0.622       0.661
C(q_5_diff)[T.2.0]                 -0.1428      0.006    -22.105      0.000      -0.155      -0.130
C(q_5_diff)[T.3.0]                 -0.2720      0.009    -30.106      0.000      -0.290      -0.254
C(q_1_diff)[T.2]                    0.0438      0.011      3.858      0.000       0.022       0.066
C(q_1_diff)[T.3]                    0.0628      0.014      4.601      0.000       0.036       0.090
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1747      0.010     17.555      0.000       0.155       0.194
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.1263      0.009     13.497      0.000       0.108       0.145
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1454      0.015      9.799      0.000       0.116       0.175
num_diff_2                         -0.0092      0.003     -2.703      0.007      -0.016      -0.003
num_diff_3                         -0.0029      0.005     -0.622      0.534      -0.012       0.006
==============================================================================
Omnibus:                   311143.051   Durbin-Watson:                   1.881
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3408.082
Skew:                          -0.576   Prob(JB):                         0.00
Kurtosis:                       1.627   Cond. No.                         13.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### analyze the drop rate in this frame

In [48]:
regdf['is_drop'] = regdf.apply(lambda _row : 1 if np.isnan(_row['q_1_corr']) != True  and  np.isnan(_row['q_5_corr']) == True else 0, axis=1)

treatment= [f"num_diff_{i}" for i in [2,3]]
conti_indep_var = ["C(q_1_corr) : C(q_1_diff)"]
conti_indep_var.extend(treatment)
OLS_estimate(regdf, dep_var='is_drop', indep_var = conti_indep_var)

                            OLS Regression Results
==============================================================================
Dep. Variable:                is_drop   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     1.515
Date:                Fri, 17 Oct 2025   Prob (F-statistic):              0.157
Time:                        10:09:47   Log-Likelihood:                 431.54
No. Observations:               27094   AIC:                            -847.1
Df Residuals:                   27086   BIC:                            -781.4
Df Model:                           7
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.0704      0.005     14.507      0.000       0.061       0.080
C(q_1_diff)[T.2]                   -0.0069      0.006     -1.211      0.226      -0.018       0.004
C(q_1_diff)[T.3]                   -0.0071      0.007     -1.046      0.296      -0.020       0.006
C(q_1_corr)[T.1]:C(q_1_diff)[1]    -0.0034      0.005     -0.683      0.495      -0.013       0.006
C(q_1_corr)[T.1]:C(q_1_diff)[2]    -0.0010      0.005     -0.210      0.834      -0.010       0.008
C(q_1_corr)[T.1]:C(q_1_diff)[3]    -0.0084      0.007     -1.128      0.259      -0.023       0.006
prop_diff_2                        -0.0079      0.005     -1.572      0.116      -0.018       0.002
prop_diff_3                        -0.0055      0.007     -0.812      0.417      -0.019       0.008
==============================================================================
Omnibus:                    19874.857   Durbin-Watson:                   1.937
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           213787.089
Skew:                           3.689   Prob(JB):                         0.00
Kurtosis:                      14.616   Cond. No.                         8.58
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [45]:
regdf['is_drop'] = regdf.apply(lambda _row : 1 if np.isnan(_row['q_1_corr']) != True  and  np.isnan(_row['q_5_corr']) == True else 0, axis=1)
conti_indep_var = ["C(q_1_corr) : C(q_1_diff)"]
OLS_estimate(regdf, dep_var='is_drop', indep_var = conti_indep_var)

                            OLS Regression Results
==============================================================================
Dep. Variable:                is_drop   R-squared:                       0.005
Model:                            OLS   Adj. R-squared:                  0.005
Method:                 Least Squares   F-statistic:                     34.83
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           1.16e-35
Time:                        10:06:08   Log-Likelihood:                -22694.
No. Observations:               36032   AIC:                         4.540e+04
Df Residuals:                   36026   BIC:                         4.545e+04
Df Model:                           5
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.3420      0.007     49.543      0.000       0.329       0.356
C(q_1_diff)[T.2]                   -0.0070      0.009     -0.774      0.439      -0.025       0.011
C(q_1_diff)[T.3]                   -0.0246      0.011     -2.277      0.023      -0.046      -0.003
C(q_1_corr)[T.1]:C(q_1_diff)[1]    -0.0699      0.008     -8.667      0.000      -0.086      -0.054
C(q_1_corr)[T.1]:C(q_1_diff)[2]    -0.0657      0.008     -8.570      0.000      -0.081      -0.051
C(q_1_corr)[T.1]:C(q_1_diff)[3]    -0.0600      0.012     -4.855      0.000      -0.084      -0.036
==============================================================================
Omnibus:                    27177.772   Durbin-Watson:                   1.762
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6911.220
Skew:                           0.901   Prob(JB):                         0.00
Kurtosis:                       1.835   Cond. No.                         7.72
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [128]:
regdf.is_drop

0        1
1        1
2        0
3        0
4        0
        ..
83818    0
83819    0
83820    1
83821    0
83822    1
Name: is_drop, Length: 83823, dtype: int64

In [126]:

if np.isnan(regdf.loc[1,'q_6_corr'] ) == True:
    print(True)

True

## in seperate  df

In [69]:
regdfs = [regdf.query(f"q_5_diff == {i}").copy() for i in [1,2,3]]
treatment = [f"num_diff_{i}" for i in [2,3]]
conti_indep_var = ["C(q_1_corr) : C(q_1_diff)"]
conti_indep_var.extend(treatment)
for df,dif in zip( regdfs,[1,2,3]):
    print(f"\n\n difficulty of question 5 == {dif} \n\n")
    OLS_estimate(df, dep_var="q_5_corr", indep_var=conti_indep_var)

 difficulty of question 5 == 1


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.025
Model:                            OLS   Adj. R-squared:                  0.024
Method:                 Least Squares   F-statistic:                     39.29
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           6.86e-55
Time:                        15:34:54   Log-Likelihood:                -5971.8
No. Observations:               10676   AIC:                         1.196e+04
Df Residuals:                   10668   BIC:                         1.202e+04
Df Model:                           7
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.6301      0.012     52.116      0.000       0.606       0.654
C(q_1_diff)[T.2]                    0.0518      0.016      3.272      0.001       0.021       0.083
C(q_1_diff)[T.3]                    0.0501      0.021      2.350      0.019       0.008       0.092
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1676      0.013     13.175      0.000       0.143       0.193
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.1187      0.014      8.341      0.000       0.091       0.147
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1396      0.025      5.525      0.000       0.090       0.189
num_diff_2                          0.0008      0.005      0.167      0.868      -0.009       0.010
num_diff_3                          0.0069      0.007      0.951      0.342      -0.007       0.021
==============================================================================
Omnibus:                     1786.912   Durbin-Watson:                   1.885
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2508.783
Skew:                          -1.160   Prob(JB):                         0.00
Kurtosis:                       2.490   Cond. No.                         13.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


 difficulty of question 5 == 2


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.027
Model:                            OLS   Adj. R-squared:                  0.026
Method:                 Least Squares   F-statistic:                     43.25
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           1.17e-60
Time:                        15:34:54   Log-Likelihood:                -7487.0
No. Observations:               10889   AIC:                         1.499e+04
Df Residuals:                   10881   BIC:                         1.505e+04
Df Model:                           7
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.4905      0.017     28.849      0.000       0.457       0.524
C(q_1_diff)[T.2]                    0.0362      0.018      1.984      0.047       0.000       0.072
C(q_1_diff)[T.3]                    0.0826      0.022      3.751      0.000       0.039       0.126
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1990      0.017     11.863      0.000       0.166       0.232
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.1500      0.014     10.505      0.000       0.122       0.178
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1412      0.023      6.027      0.000       0.095       0.187
num_diff_2                         -0.0115      0.005     -2.154      0.031      -0.022      -0.001
num_diff_3                         -0.0070      0.007     -0.942      0.346      -0.021       0.008
==============================================================================
Omnibus:                    47968.228   Durbin-Watson:                   1.895
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1643.946
Skew:                          -0.435   Prob(JB):                         0.00
Kurtosis:                       1.307   Cond. No.                         14.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


 difficulty of question 5 == 3


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.016
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     8.901
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           6.43e-11
Time:                        15:34:54   Log-Likelihood:                -2791.5
No. Observations:                3893   AIC:                             5599.
Df Residuals:                    3885   BIC:                             5649.
Df Model:                           7
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.4727      0.036     13.309      0.000       0.403       0.542
C(q_1_diff)[T.2]                    0.0342      0.036      0.960      0.337      -0.036       0.104
C(q_1_diff)[T.3]                    0.0173      0.037      0.473      0.636      -0.054       0.089
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1093      0.034      3.196      0.001       0.042       0.176
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.0711      0.025      2.860      0.004       0.022       0.120
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1565      0.031      5.059      0.000       0.096       0.217
num_diff_2                         -0.0412      0.011     -3.899      0.000      -0.062      -0.020
num_diff_3                         -0.0247      0.011     -2.179      0.029      -0.047      -0.002
==============================================================================
Omnibus:                    14193.346   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              608.450
Skew:                           0.078   Prob(JB):                    7.53e-133
Kurtosis:                       1.069   Cond. No.                         15.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### add the time control

In [70]:
regdf

,user_id,gamecharacter_id,session_id,is_correct,difficulty_level,experiment_index,question_id,subject_name,section_id,section_name,...,after_test_diff,treatment,num_diff_1,num_diff_2,num_diff_3,is_drop,prop_diff_1,prop_diff_2,prop_diff_3,treatment_length
"(-9216223767477519093, -3293706459053707777, 1)",-9216223767477519093,-3293706459053707777,1,"[0, 0, 1, 0]","[1, 3, 3, 3]","[None, None, None, None]","[941132157500741589, -2528918832815624142, 603...","[數學, 數學, 數學, 數學]","[6084119510007883763, 6084119510007883763, 522...","[4 小數的乘法, 4 小數的乘法, 2 分數的計算, 2 分數的計算]",...,NaN,"[0, 0, 3]",0.0,0.0,3.0,1,0.00,0.00,1.00,3.0
"(-9215975131138636025, 2806305522055252713, 1)",-9215975131138636025,2806305522055252713,1,"[1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, ...","[1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[5986642740406154097, -1814475752912975980, 57...","[數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數...","[-247801341597882458, -247801341597882458, -24...","[1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體...",...,1.0,"[2, 1, 0]",2.0,1.0,0.0,0,0.67,0.33,0.00,3.0
"(-9212166316050044816, 5893252723684985621, 1)",-9212166316050044816,5893252723684985621,1,"[1, 0, 1, 0, 1]","[1, 1, 2, 2, 1]","[None, None, None, None, None]","[-3982380057634078317, 6534779973756457463, -8...","[數學, 數學, 數學, 數學, 數學]","[-5730797827999106544, -1882325247118400549, 7...","[8-1 平行四邊形的面積, 9-1 分數表示整數相除的結果, 10-3 幾分之幾圖, 7-...",...,1.0,"[1, 2, 0]",1.0,2.0,0.0,0,0.33,0.67,0.00,3.0
"(-9212166316050044816, 5893252723684985621, 2)",-9212166316050044816,5893252723684985621,2,"[1, 1, 1, 1, 1, 1, 1]","[1, 2, 2, 2, 2, 1, 1]","[3, 3, 3, 3, 3, 3, 3]","[5986642740406154097, -1814475752912975980, 48...","[數學, 數學, 數學, 數學, 數學, 數學, 數學]","[-247801341597882458, -247801341597882458, -24...","[1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積]",...,2.0,"[0, 3, 0]",0.0,3.0,0.0,0,0.00,1.00,0.00,3.0
"(-9188432125589223658, -3468651825129845530, 1)",-9188432125589223658,-3468651825129845530,1,"[0, 0]","[2, 1]","[None, None]","[-8645121234103906346, 6775587959579167004]","[數學, 數學]","[1466806251755821696, 1466806251755821696]","[8 分數, 8 分數]",...,NaN,None,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(9220452508174186299, -7188733719598119482, 6)",9220452508174186299,-7188733719598119482,6,"[0, 1, 0, 1, 1, 0, 1, 1, 1]","[2, 3, 2, 1, 2, 2, 2, 2, 2]","[None, None, None, None, None, None, None, Non...","[-1814475752912975980, 6916997226709832338, 41...","[數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學]","[-247801341597882458, -247801341597882458, -24...","[1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體...",...,2.0,"[1, 1, 1]",1.0,1.0,1.0,0,0.33,0.33,0.33,3.0
"(9220452508174186299, -7188733719598119482, 7)",9220452508174186299,-7188733719598119482,7,"[0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, ...","[2, 2, 1, 1, 1, 2, 3, 2, 3, 1, 1, 3, 2, 2, 1, ...","[None, None, None, None, None, None, None, Non...","[-5531336178737327718, -4217406752547553545, 7...","[數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數...","[-247801341597882458, -247801341597882458, -24...","[1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 體...",...,1.0,"[2, 1, 0]",2.0,1.0,0.0,0,0.67,0.33,0.00,3.0
"(9220452508174186299, -7188733719598119482, 8)",9220452508174186299,-7188733719598119482,8,"[0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, ...","[2, 2, 3, 3, 2, 3, 3, 3, 3, 2, 3, 1, 1, 2, 1, ...","[None, None, None, None, None, None, None, Non...","[6343617583593649937, -5531336178737327718, -3...","[數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數...","[4953200353615914529, -247801341597882458, -24...","[1-3 數的十進位結構, 1 體積, 1 體積, 1 體積, 1 體積, 1 體積, 1 ...",...,2.0,"[0, 1, 2]",0.0,1.0,2.0,0,0.00,0.33,0.67,3.0
"(9220452508174186299, -7188733719598119482, 9)",9220452508174186299,-7188733719598119482,9,[0],[2],[2],[5214900591100106728],[數學],[-724883818906726236],[7 表面積],...,NaN,None,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN
"(9223087356083948458, 8730877631531542123, 1)",9223087356083948458,8730877631531542123,1,"[1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0]","[1, 1, 2, 3, 1, 1, 2, 1, 1, 2, 2]","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]","[-2451827522348391739, -4540872921350567508, -...","[數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學, 數學]","[6084119510007883763, -9042528178512436726, 60...","[4 小數的乘法, 5 十進位結構, 4 小數的乘法, 4 小數的乘法, 4 小數的乘法, ...",...,1.0,"[1, 1, 1]",1.0,1.0,1.0,0,0.33,0.33,0.33,3.0

In [81]:
regdfs = [regdf.query(f"q_5_diff == {i}").copy() for i in [1,2,3]]
treatment = [f"num_diff_{i}" for i in [2,3]]
conti_indep_var = ["C(q_1_corr) : C(q_1_diff)",'treatment_time_cost','q5_time_cost']
conti_indep_var.extend(treatment)
for df,dif in zip( regdfs,[1,2,3]):
    print(len(df.index))
    df['treatment_time_cost'] = df['time_diff'].apply(lambda x : np.sum(x[1:4])/60 if len(x) > 3 else None)
    df['q5_time_cost'] = df['time_diff'].apply(lambda x : x[4]/60 if len(x) > 4 else None)
    print(f"\n\n difficulty of question 5 == {dif} \n\n")
    OLS_estimate(df, dep_var="q_5_corr", indep_var=conti_indep_var)

10676


 difficulty of question 5 == 1


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.025
Model:                            OLS   Adj. R-squared:                  0.025
Method:                 Least Squares   F-statistic:                     30.86
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           7.40e-54
Time:                        15:59:02   Log-Likelihood:                -5970.5
No. Observations:               10676   AIC:                         1.196e+04
Df Residuals:                   10666   BIC:                         1.203e+04
Df Model:                           9
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.6268      0.013     49.900      0.000       0.602       0.651
C(q_1_diff)[T.2]                    0.0518      0.016      3.272      0.001       0.021       0.083
C(q_1_diff)[T.3]                    0.0499      0.021      2.343      0.019       0.008       0.092
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1675      0.013     13.170      0.000       0.143       0.192
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.1187      0.014      8.340      0.000       0.091       0.147
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1398      0.025      5.535      0.000       0.090       0.189
treatment_time_cost                 0.0016      0.001      1.548      0.122      -0.000       0.004
q5_time_cost                       -0.0015      0.002     -0.778      0.436      -0.005       0.002
num_diff_2                          0.0008      0.005      0.161      0.872      -0.009       0.010
num_diff_3                          0.0071      0.007      0.980      0.327      -0.007       0.021
==============================================================================
Omnibus:                     1785.605   Durbin-Watson:                   1.886
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2507.928
Skew:                          -1.160   Prob(JB):                         0.00
Kurtosis:                       2.491   Cond. No.                         38.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
10889


 difficulty of question 5 == 2


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.027
Method:                 Least Squares   F-statistic:                     35.04
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           1.20e-61
Time:                        15:59:02   Log-Likelihood:                -7480.8
No. Observations:               10889   AIC:                         1.498e+04
Df Residuals:                   10879   BIC:                         1.505e+04
Df Model:                           9
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.4761      0.017     27.229      0.000       0.442       0.510
C(q_1_diff)[T.2]                    0.0369      0.018      2.021      0.043       0.001       0.073
C(q_1_diff)[T.3]                    0.0823      0.022      3.740      0.000       0.039       0.125
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1984      0.017     11.830      0.000       0.166       0.231
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.1499      0.014     10.503      0.000       0.122       0.178
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1415      0.023      6.042      0.000       0.096       0.187
treatment_time_cost                 0.0038      0.001      3.066      0.002       0.001       0.006
q5_time_cost                        0.0032      0.003      1.280      0.201      -0.002       0.008
num_diff_2                         -0.0109      0.005     -2.047      0.041      -0.021      -0.000
num_diff_3                         -0.0063      0.007     -0.858      0.391      -0.021       0.008
==============================================================================
Omnibus:                    48187.343   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1637.227
Skew:                          -0.435   Prob(JB):                         0.00
Kurtosis:                       1.311   Cond. No.                         34.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
3893


 difficulty of question 5 == 3


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.017
Model:                            OLS   Adj. R-squared:                  0.015
Method:                 Least Squares   F-statistic:                     7.364
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           1.02e-10
Time:                        15:59:02   Log-Likelihood:                -2789.6
No. Observations:                3893   AIC:                             5599.
Df Residuals:                    3883   BIC:                             5662.
Df Model:                           9
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.4634      0.036     12.928      0.000       0.393       0.534
C(q_1_diff)[T.2]                    0.0338      0.036      0.949      0.343      -0.036       0.104
C(q_1_diff)[T.3]                    0.0164      0.037      0.449      0.653      -0.055       0.088
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1083      0.034      3.167      0.002       0.041       0.175
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.0700      0.025      2.818      0.005       0.021       0.119
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1561      0.031      5.043      0.000       0.095       0.217
treatment_time_cost                 0.0017      0.002      0.855      0.393      -0.002       0.006
q5_time_cost                        0.0073      0.004      1.649      0.099      -0.001       0.016
num_diff_2                         -0.0417      0.011     -3.946      0.000      -0.062      -0.021
num_diff_3                         -0.0258      0.011     -2.264      0.024      -0.048      -0.003
==============================================================================
Omnibus:                    14228.314   Durbin-Watson:                   1.897
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              606.110
Skew:                           0.078   Prob(JB):                    2.43e-132
Kurtosis:                       1.073   Cond. No.                         40.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### add the control variable to control the heteroristic of time effect

In [83]:
regdfs = [regdf.query(f"q_5_diff == {i}").copy() for i in [1,2,3]]
treatment = [f"num_diff_{i}*treatment_time_cost" for i in [2,3]]
conti_indep_var = ["C(q_1_corr) : C(q_1_diff)",'q5_time_cost']
conti_indep_var.extend(treatment)
for df,dif in zip( regdfs,[1,2,3]):
    print(len(df.index))
    df['treatment_time_cost'] = df['time_diff'].apply(lambda x : np.sum(x[1:4])/60 if len(x) > 3 else None)
    df['q5_time_cost'] = df['time_diff'].apply(lambda x : x[4]/60 if len(x) > 4 else None)
    print(f"\n\n difficulty of question 5 == {dif} \n\n")
    OLS_estimate(df, dep_var="q_5_corr", indep_var=conti_indep_var)

10676


 difficulty of question 5 == 1


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.025
Model:                            OLS   Adj. R-squared:                  0.024
Method:                 Least Squares   F-statistic:                     25.27
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           2.03e-52
Time:                        16:24:33   Log-Likelihood:                -5970.4
No. Observations:               10676   AIC:                         1.196e+04
Df Residuals:                   10664   BIC:                         1.205e+04
Df Model:                          11
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.6267      0.013     47.231      0.000       0.601       0.653
C(q_1_diff)[T.2]                    0.0517      0.016      3.268      0.001       0.021       0.083
C(q_1_diff)[T.3]                    0.0500      0.021      2.345      0.019       0.008       0.092
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1676      0.013     13.170      0.000       0.143       0.192
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.1187      0.014      8.339      0.000       0.091       0.147
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1399      0.025      5.535      0.000       0.090       0.189
q5_time_cost                       -0.0015      0.002     -0.774      0.439      -0.005       0.002
num_diff_2                          0.0014      0.006      0.237      0.812      -0.010       0.013
treatment_time_cost                 0.0016      0.002      0.903      0.367      -0.002       0.005
num_diff_2:treatment_time_cost     -0.0002      0.001     -0.192      0.847      -0.003       0.002
num_diff_3                          0.0049      0.009      0.547      0.584      -0.013       0.022
num_diff_3:treatment_time_cost      0.0008      0.002      0.434      0.665      -0.003       0.004
==============================================================================
Omnibus:                     1785.466   Durbin-Watson:                   1.886
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2507.851
Skew:                          -1.160   Prob(JB):                         0.00
Kurtosis:                       2.491   Cond. No.                         61.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
10889


 difficulty of question 5 == 2


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.027
Method:                 Least Squares   F-statistic:                     28.83
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           1.81e-60
Time:                        16:24:33   Log-Likelihood:                -7479.9
No. Observations:               10889   AIC:                         1.498e+04
Df Residuals:                   10877   BIC:                         1.507e+04
Df Model:                          11
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.4685      0.019     24.894      0.000       0.432       0.505
C(q_1_diff)[T.2]                    0.0374      0.018      2.046      0.041       0.002       0.073
C(q_1_diff)[T.3]                    0.0827      0.022      3.757      0.000       0.040       0.126
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1987      0.017     11.847      0.000       0.166       0.232
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.1497      0.014     10.488      0.000       0.122       0.178
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1414      0.023      6.035      0.000       0.095       0.187
q5_time_cost                        0.0031      0.003      1.240      0.215      -0.002       0.008
num_diff_2                         -0.0059      0.007     -0.899      0.369      -0.019       0.007
treatment_time_cost                 0.0064      0.003      2.424      0.015       0.001       0.012
num_diff_2:treatment_time_cost     -0.0018      0.001     -1.290      0.197      -0.005       0.001
num_diff_3                         -0.0053      0.009     -0.580      0.562      -0.023       0.013
num_diff_3:treatment_time_cost     -0.0003      0.002     -0.164      0.869      -0.004       0.003
==============================================================================
Omnibus:                    48204.670   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1636.439
Skew:                          -0.435   Prob(JB):                         0.00
Kurtosis:                       1.311   Cond. No.                         64.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
3893


 difficulty of question 5 == 3


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.018
Model:                            OLS   Adj. R-squared:                  0.015
Method:                 Least Squares   F-statistic:                     6.306
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           2.04e-10
Time:                        16:24:33   Log-Likelihood:                -2788.0
No. Observations:                3893   AIC:                             5600.
Df Residuals:                    3881   BIC:                             5675.
Df Model:                          11
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.4621      0.039     11.905      0.000       0.386       0.538
C(q_1_diff)[T.2]                    0.0336      0.036      0.943      0.346      -0.036       0.103
C(q_1_diff)[T.3]                    0.0165      0.037      0.451      0.652      -0.055       0.088
C(q_1_corr)[T.1]:C(q_1_diff)[1]     0.1087      0.034      3.178      0.001       0.042       0.176
C(q_1_corr)[T.1]:C(q_1_diff)[2]     0.0702      0.025      2.824      0.005       0.021       0.119
C(q_1_corr)[T.1]:C(q_1_diff)[3]     0.1553      0.031      5.017      0.000       0.095       0.216
q5_time_cost                        0.0073      0.004      1.655      0.098      -0.001       0.016
num_diff_2                         -0.0361      0.013     -2.789      0.005      -0.062      -0.011
treatment_time_cost                 0.0022      0.006      0.365      0.716      -0.010       0.014
num_diff_2:treatment_time_cost     -0.0019      0.003     -0.680      0.496      -0.007       0.004
num_diff_3                         -0.0341      0.014     -2.400      0.016      -0.062      -0.006
num_diff_3:treatment_time_cost      0.0027      0.003      0.886      0.376      -0.003       0.009
==============================================================================
Omnibus:                    14257.916   Durbin-Watson:                   1.895
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              604.126
Skew:                           0.078   Prob(JB):                    6.54e-132
Kurtosis:                       1.076   Cond. No.                         78.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# Neurons network test
- construct neuro network
- training from the whole sample
- use batch - LOO exam the model
- results explanation of different nodes

### calculate avg. difficultly 1 time cost

In [113]:
sumlis = []
for idx,row in regdf.iterrows():
    for i in range(1,6):
        if row[f'q_{i}_diff'] == 3:
            val = row['time_diff'][i-1]
            sumlis.append(val)
sumlis = pd.Series(sumlis)
sumlis = sumlis.apply(lambda x : x/60 if x is not None else None)
sumlis.describe()

count     22112.00
mean       1591.38
std        6811.57
min           0.00
25%           0.27
50%           0.67
75%           5.53
max      151194.05
dtype: float64

In [105]:
THREADHOLD_EASY_TOOLONG = 60 * 6
THREADHOLD_HARD_TOOSHORT = 60 * 0.27

In [112]:
regdfs = [regdf.query(f"q_5_diff == {i}").copy() for i in [1,2,3]]
treatment = [f"num_diff_{i}" for i in [2,3]]
conti_indep_var = ["C(q_1_corr) : C(q_1_diff)",'q5_time_cost','treatment_time_cost*C(is_lazy)']
conti_indep_var.extend(treatment)
for df,dif in zip( regdfs,[1,2,3]):
    print(len(df.index))
    df['treatment_time_cost'] = df['time_diff'].apply(lambda x : np.sum(x[1:4])/60 if len(x) > 3 else None)
    df['q5_time_cost'] = df['time_diff'].apply(lambda x : x[4]/60 if len(x) > 4 else None)
    df['is_lazy_easy'] = df.apply(lambda row : 1 if len(row['time_diff']) > 4 and
                                            (
                                               (row['q_2_diff'] == 1 and row['time_diff'][1]>=THREADHOLD_EASY_TOOLONG)
                                            or (row['q_3_diff'] == 1 and row['time_diff'][2]>=THREADHOLD_EASY_TOOLONG)
                                            or (row['q_4_diff'] == 1 and row['time_diff'][3]>=THREADHOLD_EASY_TOOLONG)
                                            )
                                            else 0
                             ,axis = 1
                             )
    df['is_lazy_hard'] = df.apply(lambda row : 1 if len(row['time_diff']) > 4 and
                                            (
                                               (row['q_2_diff'] == 3 and row['time_diff'][1]<=THREADHOLD_HARD_TOOSHORT)
                                            or (row['q_3_diff'] == 3 and row['time_diff'][2]<=THREADHOLD_HARD_TOOSHORT)
                                            or (row['q_4_diff'] == 3 and row['time_diff'][3]<=THREADHOLD_HARD_TOOSHORT)
                                            )
                                            else 0
                             ,axis = 1
                             )
    df['is_lazy'] = df.apply(lambda row: 1 if row['is_lazy_easy'] == 1 or row['is_lazy_hard'] == 1 else 0,axis = 1)
    print(f"\n\n difficulty of question 5 == {dif} \n\n")
    OLS_estimate(df, dep_var="q_5_corr", indep_var=conti_indep_var)

10676


 difficulty of question 5 == 1


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.026
Model:                            OLS   Adj. R-squared:                  0.025
Method:                 Least Squares   F-statistic:                     26.18
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           1.76e-54
Time:                        16:59:08   Log-Likelihood:                -5965.5
No. Observations:               10676   AIC:                         1.195e+04
Df Residuals:                   10664   BIC:                         1.204e+04
Df Model:                          11
Covariance Type:            nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
Intercept                               0.6294      0.013     49.767      0.000       0.605       0.654
C(is_lazy)[T.1]                        -0.0508      0.018     -2.845      0.004      -0.086      -0.016
C(q_1_diff)[T.2]                        0.0516      0.016      3.264      0.001       0.021       0.083
C(q_1_diff)[T.3]                        0.0496      0.021      2.328      0.020       0.008       0.091
C(q_1_corr)[T.1]:C(q_1_diff)[1]         0.1660      0.013     13.046      0.000       0.141       0.191
C(q_1_corr)[T.1]:C(q_1_diff)[2]         0.1180      0.014      8.296      0.000       0.090       0.146
C(q_1_corr)[T.1]:C(q_1_diff)[3]         0.1384      0.025      5.479      0.000       0.089       0.188
q5_time_cost                           -0.0016      0.002     -0.812      0.417      -0.006       0.002
treatment_time_cost                     0.0019      0.001      1.265      0.206      -0.001       0.005
treatment_time_cost:C(is_lazy)[T.1]     0.0013      0.002      0.605      0.545      -0.003       0.006
num_diff_2                              0.0002      0.005      0.032      0.975      -0.009       0.010
num_diff_3                              0.0193      0.008      2.304      0.021       0.003       0.036
==============================================================================
Omnibus:                     1781.014   Durbin-Watson:                   1.888
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2502.139
Skew:                          -1.158   Prob(JB):                         0.00
Kurtosis:                       2.493   Cond. No.                         42.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
10889


 difficulty of question 5 == 2


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.030
Model:                            OLS   Adj. R-squared:                  0.029
Method:                 Least Squares   F-statistic:                     30.18
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           1.68e-63
Time:                        16:59:09   Log-Likelihood:                -7472.7
No. Observations:               10889   AIC:                         1.497e+04
Df Residuals:                   10877   BIC:                         1.506e+04
Df Model:                          11
Covariance Type:            nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
Intercept                               0.4825      0.018     27.498      0.000       0.448       0.517
C(is_lazy)[T.1]                        -0.0678      0.017     -3.878      0.000      -0.102      -0.034
C(q_1_diff)[T.2]                        0.0364      0.018      1.994      0.046       0.001       0.072
C(q_1_diff)[T.3]                        0.0820      0.022      3.728      0.000       0.039       0.125
C(q_1_corr)[T.1]:C(q_1_diff)[1]         0.1967      0.017     11.733      0.000       0.164       0.230
C(q_1_corr)[T.1]:C(q_1_diff)[2]         0.1485      0.014     10.405      0.000       0.121       0.176
C(q_1_corr)[T.1]:C(q_1_diff)[3]         0.1415      0.023      6.044      0.000       0.096       0.187
q5_time_cost                            0.0029      0.003      1.152      0.249      -0.002       0.008
treatment_time_cost                     0.0010      0.002      0.606      0.545      -0.002       0.004
treatment_time_cost:C(is_lazy)[T.1]     0.0077      0.003      3.019      0.003       0.003       0.013
num_diff_2                             -0.0096      0.005     -1.781      0.075      -0.020       0.001
num_diff_3                              0.0095      0.008      1.122      0.262      -0.007       0.026
==============================================================================
Omnibus:                    48459.563   Durbin-Watson:                   1.897
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1628.434
Skew:                          -0.434   Prob(JB):                         0.00
Kurtosis:                       1.316   Cond. No.                         36.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
3893


 difficulty of question 5 == 3


                            OLS Regression Results
==============================================================================
Dep. Variable:               q_5_corr   R-squared:                       0.018
Model:                            OLS   Adj. R-squared:                  0.015
Method:                 Least Squares   F-statistic:                     6.319
Date:                Fri, 17 Oct 2025   Prob (F-statistic):           1.92e-10
Time:                        16:59:09   Log-Likelihood:                -2787.9
No. Observations:                3893   AIC:                             5600.
Df Residuals:                    3881   BIC:                             5675.
Df Model:                          11
Covariance Type:            nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
Intercept                               0.4689      0.036     13.031      0.000       0.398       0.539
C(is_lazy)[T.1]                        -0.0423      0.025     -1.698      0.090      -0.091       0.007
C(q_1_diff)[T.2]                        0.0333      0.036      0.935      0.350      -0.037       0.103
C(q_1_diff)[T.3]                        0.0157      0.037      0.430      0.667      -0.056       0.087
C(q_1_corr)[T.1]:C(q_1_diff)[1]         0.1061      0.034      3.101      0.002       0.039       0.173
C(q_1_corr)[T.1]:C(q_1_diff)[2]         0.0683      0.025      2.742      0.006       0.019       0.117
C(q_1_corr)[T.1]:C(q_1_diff)[3]         0.1549      0.031      5.001      0.000       0.094       0.216
q5_time_cost                            0.0067      0.004      1.492      0.136      -0.002       0.015
treatment_time_cost                     0.0010      0.003      0.372      0.710      -0.004       0.006
treatment_time_cost:C(is_lazy)[T.1]     0.0018      0.004      0.421      0.673      -0.007       0.010
num_diff_2                             -0.0413      0.011     -3.884      0.000      -0.062      -0.020
num_diff_3                             -0.0172      0.012     -1.385      0.166      -0.042       0.007
==============================================================================
Omnibus:                    14258.117   Durbin-Watson:                   1.900
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              604.062
Skew:                           0.078   Prob(JB):                    6.75e-132
Kurtosis:                       1.076   Cond. No.                         42.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.